eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
micorservices:
  course-service:
    endpoints:
      endpoint:
        uri: http://COURSE-SERVICE/course/createCourse

    
